#creates the dl_node object file
dl_node: dl_node.h dl_node.cpp
	g++ -Wall -g -c dl_node.cpp

#creates the dl_list object file	
dl_list: dl_list.cpp dl_list.h
	g++ -Wall -g -c dl_list.cpp
	
#removes all object files and exe	
clean:
	rm *.o